# Site settings
title: Jaromin Guitars
email: guitars@jaromin.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: pjaromin
github_username:  pjaromin

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/posts/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Gems
gems: [jekyll-paginate]